# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site title
title: "Costoda Blog - Code, bits, and thoughts of Aaron LaBeau"

# A description of your site for social meta tag, search engines, and feed.xml
description: "Aaron LaBeau is a Senior Developer Advocate. Loves Xamarin, Visual Studio, Android Studio, XCode, Kotlin, Swift, and IoT programming. Opinions are my own.  When not coding I'm slaying Orcs, hording gold, running D&D games, playing guitar, or handing out with my wife and dogs."


# The subpath of your site, e.g. /blog, for generating urls
baseurl: 
# baseurl: 

navigation:
- text: Home
  url: /#home
- text: about
  url: /#about
- text: Videos 
  url: /#videos
- text: Blog
  url: /#blog

sass:
  sass_dir: _sass

# The base hostname & protocol of your site for where absolute urls are needed
url: "https://www.costoda.tech"

# The shortname for your Disqus site to enable comments.
disqus:

# Author information - author info at the bottom of the post
author_name: "Aaron LaBeau"

# Social links in the site footer
twitter_username: "biozal"
facebook_username: "biozal"
pinterest_username: "biozal"
linkedin_username: "biozal"
